# ControlGym Matrices

This notebook prints the actual matrices behind the environments in `controlgym`.

It shows:
- the discrete-time matrices used by `controlgym.make(...)`
- the derived quadratic cost matrices `Q`, `R`, and `S`


In [1]:
from pathlib import Path
import importlib.resources as pkg_resources

import numpy as np
import scipy.io as sio
from controlgym.envs import linear_control_src, make

np.set_printoptions(precision=5, suppress=True, linewidth=160)


In [2]:
env_id = "ac6"
sample_time = 0.1
noise_cov = 0.1
random_init_state_cov = 0.1


In [3]:
def show_matrix(name, matrix):
    matrix = np.asarray(matrix)
    print(f"{name}: shape={matrix.shape}")
    print(matrix)
    print()


In [4]:
with pkg_resources.path(linear_control_src, f"{env_id}.mat") as mat_path:
    mat_path = Path(mat_path)
    raw = sio.loadmat(mat_path)

print(f"Loaded raw file: {mat_path}")
print()

for key in ["A", "B1", "B2", "C", "C1", "D11", "D12", "D21", "x_0"]:
    if key in raw:
        show_matrix(f"raw[{key}]", raw[key])


Loaded raw file: /Users/schoi/Documents/repos/controlgym/controlgym/envs/linear_control_src/ac6.mat

raw[A]: shape=(10, 10)
[[ -0.01365   0.178     0.00017  -0.561    -0.03726   0.        0.01365  -0.01311   0.       -1.     ]
 [ -0.01516  -0.752     1.001     0.00127  -0.06311   0.        0.01516   0.05536   0.        0.     ]
 [  0.00107   0.07896  -0.8725    0.       -3.399     0.       -0.00107  -0.00581   0.        0.     ]
 [  0.        0.        1.        0.        0.        0.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.      -20.       10.72      0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.      -50.        0.        0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.       -0.4447    0.        0.        0.     ]
 [  0.        0.        0.        0.        0.        0.        0.       -0.4447    0.0044    0.     ]
 [  0.        0.        0.        0.        0.      

In [5]:
env = make(
    env_id,
    sample_time=sample_time,
    noise_cov=noise_cov,
    random_init_state_cov=random_init_state_cov,
)

print(f"Instantiated controlgym env: {env_id}")
print(f"sample_time={env.sample_time}")
print(f"noise_cov={env.noise_cov}")
print(f"random_init_state_cov={env.random_init_state_cov}")
print(f"n_state={env.n_state}, n_disturbance={env.n_disturbance}, n_action={env.n_action}, n_observation={env.n_observation}")
print(f"spectral_radius(A)={np.max(np.abs(np.linalg.eigvals(env.A))):.6f}")


Instantiated controlgym env: ac6
sample_time=0.1
noise_cov=0.1
random_init_state_cov=0.1
n_state=10, n_disturbance=10, n_action=4, n_observation=5
spectral_radius(A)=1.001223


In [6]:
show_matrix("env.A", env.A)
show_matrix("env.B1", env.B1)
show_matrix("env.B2", env.B2)
show_matrix("env.C", env.C)
show_matrix("env.C1", env.C1)
show_matrix("env.D11", env.D11)
show_matrix("env.D12", env.D12)
show_matrix("env.D21", env.D21)


env.A: shape=(10, 10)
[[ 0.99862  0.01713 -0.00186 -0.05606 -0.0015  -0.0003   0.00135 -0.00123 -0.      -0.09993]
 [-0.00145  0.92791  0.09231  0.00016 -0.01168 -0.00193  0.00142  0.00519  0.       0.00007]
 [ 0.0001   0.00728  0.91681 -0.      -0.13885 -0.02711 -0.00009 -0.00052 -0.      -0.00001]
 [ 0.00001  0.00037  0.09577  1.      -0.00934 -0.00146 -0.      -0.00003 -0.      -0.     ]
 [ 0.       0.       0.       0.       0.13534  0.04595  0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.00674  0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.9565   0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.9565   0.00042  0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.      -0.00042  0.9565   0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.       0.       1.     ]]

env.B1: shape=(10, 10)
[[ 0.00006 -0.00007 -0.

In [7]:
show_matrix("env.Q", env.Q)
show_matrix("env.R", env.R)
show_matrix("env.S", env.S)
show_matrix("env.init_state", env.init_state)


env.Q: shape=(10, 10)
[[ 1.00004  0.00207 -0.00022  0.      -0.00067  0.      -1.00004 -0.00015  0.       0.     ]
 [ 0.00207  0.10259 -0.01076  0.      -0.03305  0.      -0.00207 -0.00755  0.       0.     ]
 [-0.00022 -0.01076  0.00113  0.       0.00347  0.       0.00022  0.00079  0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.       0.       0.     ]
 [-0.00067 -0.03305  0.00347  0.       0.01065  0.       0.00067  0.00243  0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.       0.       0.     ]
 [-1.00004 -0.00207  0.00022  0.       0.00067  0.       1.00004  0.00015  0.       0.     ]
 [-0.00015 -0.00755  0.00079  0.       0.00243  0.       0.00015  0.00056  0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.       0.       0.     ]]

env.R: shape=(4, 4)
[[8. 0. 0. 0.]
 [0. 8. 0. 